import express from 'express';
import authRoutes from './auth.routes.js';
import userRoutes from './user.routes.js';
import listenerRoutes from './listener.routes.js';
import languageRoutes from './language.routes.js';
import coinPackRoutes from './coin-pack.routes.js';
import walletRoutes from './wallet.routes.js';
import followRoutes from './follow.routes.js';
import companyRoutes from './company.routes.js';
import giftRoutes from './gift.routes.js';
import chatRoutes from './chat.routes.js';
import bannerRoutes from './banner.routes.js';
import wishlistRoutes from './wishlist.routes.js';
import dailyRewardRoutes from './daily-reward.routes.js';
import avatarRoutes from './avatar.routes.js';
import callRoutes from './call.routes.js';
import liveRoomRoutes from './live-room.routes.js';
import stickerCategoryRoutes from './sticker-category.routes.js';
import stickerRoutes from './sticker.routes.js';
import reviewRoutes from './review.routes.js';
import feedbackRoutes from './feedback.routes.js';
import reportRoutes from './report.routes.js';
import referralRoutes from './referral.routes.js';
import withdrawalRoutes from './withdrawal.routes.js';
import anchorLevelRoutes from './anchor-level.routes.js';
import notificationRoutes from './notification.routes.js';
import xpRoutes from './xp.routes.js';
import searchRoutes from './search.routes.js';
import homeRoutes from './home.routes.js';
import matchRoutes from './match.routes.js';
import agentRoutes from './agent.routes.js';
import analyticsRoutes from './analytics.routes.js';
import adminDashboardRoutes from './admin-dashboard.routes.js';
import communicationRoutes from './communication.routes.js';
import countryRoutes from './country.routes.js';

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/countries', countryRoutes);
router.use('/home', homeRoutes);
router.use('/match', matchRoutes);
router.use('/agent', agentRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/admin', adminDashboardRoutes);
router.use('/communications', communicationRoutes);
router.use('/users', userRoutes);
router.use('/listeners', listenerRoutes);
router.use('/languages', languageRoutes);
router.use('/coin-packs', coinPackRoutes);
router.use('/wallets', walletRoutes);
router.use('/follows', followRoutes);
router.use('/company', companyRoutes);
router.use('/gifts', giftRoutes);
router.use('/chats', chatRoutes);
router.use('/banners', bannerRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/daily-rewards', dailyRewardRoutes);
router.use('/avatars', avatarRoutes);
router.use('/calls', callRoutes);
router.use('/live-rooms', liveRoomRoutes);
router.use('/sticker-categories', stickerCategoryRoutes);
router.use('/stickers', stickerRoutes);
router.use('/reviews', reviewRoutes);
router.use('/feedback', feedbackRoutes);
router.use('/reports', reportRoutes);
router.use('/referrals', referralRoutes);
router.use('/withdrawals', withdrawalRoutes);
router.use('/anchor-levels', anchorLevelRoutes);
router.use('/notifications', notificationRoutes);
router.use('/xp', xpRoutes);
router.use('/search', searchRoutes);

export default router;

